### ISSUE TITLE
[BUG] "The application is not responding"

### ISSUE THREAD

**Issue by smotim** [Vysp3r/ProtonPlus#27]
**Describe the bug**
the message "The application is not responding" appears when I click on the plus button next to Installed tools. After a while, the choice of the Proton version appears. But during this time, the message "the application is not responding" may appear several times. Probably someone during this time may think that the application is broken and delete it

**Desktop (please complete the following information):**
 - Fedora 36
 - GNOME 42
 - Flatpak

**Additional context**
Thanks for the app, I've been looking for an analogue of proton-qt-up on gtk for a long time

**Comment by Vysp3r** [comment]
What version are you using?

**Comment by smotim** [comment]
0.2.0, Steam(flatpak). I checked the other two, there is exactly the same problem. And the main application window, by the way, also freezes for 10-20 seconds until the proton version selection opens. (I mean, I can't even move the window to another place on the screen)

**Comment by Vysp3r** [comment]
It's working fine for me on a vanilla VM of Fedora 36 with Steam (Flatpak). I don't have any of the problems you seems to have. Can you run the application using `flatpak run com.vysp3r.ProtonPlus` and show me the logs. Thanks you!

**Comment by smotim** [comment]
```
(protonplus:2): Gtk-CRITICAL **: 23:04:04.105: gtk_list_box_bind_model: assertion 'GTK_IS_LIST_BOX (box)' failed
(protonplus:2): Gtk-CRITICAL **: 23:04:04.105: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
(protonplus:2): Adwaita-CRITICAL **: 23:04:12.488: adw_combo_row_set_model: assertion 'ADW_IS_COMBO_ROW (self)' failed
```
1 and 2 appear immediately at startup, and 3 only while waiting for the window with the choice of the Proton version

**Comment by Vysp3r** [comment]
Does the window to install new versions open at all or it crashes before that?

**Comment by smotim** [comment]
It opens, just the application freezes for 20 seconds at this moment. During this time, the system manages to offer to close it

**Comment by Vysp3r** [comment]
So the application freezes once you press the button to add a new version?

**Comment by smotim** [comment]
Yes. All other functions seem to work fine

**Comment by Vysp3r** [comment]
Have you tried to delete the folder ~/.var/app/com.vysp3r.ProtonPlus and then reinstalling it?

**Comment by Vysp3r** [comment]
Have you messed with the permissions using Flatseal or you didn't touch that?

**Comment by smotim** [comment]
> Have you tried to delete the folder ~/.var/app/com.vysp3r.ProtonPlus and then reinstalling it?

I tried it. Nothing has changed



> Have you messed with the permissions using Flatseal or you didn't touch that?

I only have Flatseal installed, but I haven't touched anything in it

**Comment by smotim** [comment]
Once I built a Telegrand, I'll try it now :)

**Comment by smotim** [comment]
The same errors in the terminal. 
And, I'm very sorry. I accidentally wrote the wrong version of the system. I have fedora 37+Gnome 43

**Comment by smotim** [comment]
By the way, when launching the application in the terminal, I noticed another message after completing the installation of an additional version of Proton GE. It seems that for some reason the application copies Proton twice or something.
`
An error occurred while moving the /home/team/ file.var/app/com.valvesoftware.Steam/dota/Steam/compatibility tools.d/GE-Proton7-37: The file exists`

The error text may be slightly different, this is a translation from my native language

**Comment by Vysp3r** [comment]
It still should works fine on F37 :/ 
Can you go in Builder and switch the active configuration to Default instead of com.vysp3r.ProtonPlus. You can change that by using the drop down arrow on the left side of the start button, NOT the one the right side of the start button.

**Comment by Vysp3r** [comment]
I know of that problem, I'm currently working on that. I basically rename the folders after extracting them, but for GE-Proton, I try to rename it with the same name. That's why that error happens. It's an easy fix and it shouldn't crash the application.

**Comment by smotim** [comment]
This time the build stopped at this stage. The "export" button, through which I used to get flatpak for installation, is now inactive. Did I do something wrong?

`[26/26] Linking target src/protonplus`

**Comment by Vysp3r** [comment]
When you're using the Default config, it's basically building for your system and not flatpak, so that's why you can't export it. Just press the play button, not the build button.

**Comment by smotim** [comment]
Sorry, I could have guessed it myself. I started it, again the same errors in the terminal and the same problem with freezing

**Comment by Vysp3r** [comment]
Wait, I just read the logs again. You did manage to open the window and install a tool right?

**Comment by Vysp3r** [comment]
So it does not crash every time you press on the button with a plus on it?

**Comment by smotim** [comment]
Absolutely right. The application as a whole works. But before choosing the proton version, it freezes for a very long time

**Comment by Vysp3r** [comment]
Once you're on the install page (https://github.com/Vysp3r/ProtonPlus/blob/main/Preview-2.png), are you able to see a list of the tools and a list of the versions or it crashes before you can do anything?

**Comment by smotim** [comment]
I can. Nothing breaks. The whole app is working. The only problem is that this window has to wait 20 seconds, and during this time the window pops up several times "the application is not responding. don't you want to close it?"

**Comment by Vysp3r** [comment]
Ohhhh I see, I didn't understand correctly what you meant at all sorry. That is still weird because the extraction and downloading is done from another thread, so the main thread which renders the application shouldn't freeze like that. I guess you can't see a progress bar while it's downloading and extracting that shows the progress because of that?

**Comment by Vysp3r** [comment]
But it doesn't update because the application hangs?

**Comment by smotim** [comment]
Updates. The application freezes between clicking on "+" and a window with a list of versions appears. The rest of the time, everything seems to work as intended.

**Comment by smotim** [comment]
If it's difficult to understand me, I can record a video and send a link

**Comment by Vysp3r** [comment]
Oh yeah a gif or a video would be nice since I can't reproduce on my side!

**Comment by Vysp3r** [comment]
May I know your PC Specs and Internet speed? The only reason I can think of is maybe that your connection speed is slow so the application as to wait to query the versions from GitHub and then adding them to the list. That would result in the application hanging if it's not done super fast.

**Comment by Vysp3r** [comment]
I tested on a VM with only two cores and I get your problem, just not for 20 seconds but for like 3 seconds. I will make sure in the next update to process the data in a background thread to avoid the application from hanging at that specific place. I have to go work at my second job soon, but after that I will fix that a push an update tomorrow with some other fixes. I'll keep that issue open for now, until you confirm it's not present anymore.

**Comment by smotim** [comment]
https://youtu.be/GykeTUfxZEk

**Comment by Vysp3r** [comment]
Yeah I got something like that on my VM, I'll publish an update tonight like I said to fix that and some other stuff. Thank you a lot for your time. Nice GNOME between :)

**Comment by smotim** [comment]
Thank you. And for the application, and for, perhaps, help. The problem is definitely not on the Internet. I have 500 megabits, and the application loads Proton at a slower speed. The same thing happened through VPN from several other countries.  CPU and RAM usage I think you've seen in the video.

**Comment by Vysp3r** [comment]
I pushed a fix in the dev branch. Would you be able to test it out on your end to see if it fixes your problem?

**Comment by smotim** [comment]
```
(protonplus:15067): Gtk-CRITICAL **: 14:07:30.156: gtk_list_box_bind_model: assertion 'GTK_IS_LIST_BOX (box)' failed

(protonplus:15067): Gtk-CRITICAL **: 14:07:30.156: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed
```
Hello. I tried it. The third error in the terminal stopped appearing, but the problem persisted

**Comment by smotim** [comment]
Errors stopped appearing after the [last commit](https://github.com/Vysp3r/ProtonPlus/commit/ca391c32c2a4e382208b0febf956f22f64ac0ca0). But the problem persisted. Maybe the program began to unfreeze a little faster. But it's still at least 10 seconds and the "application is not responding" window appears

**Comment by Vysp3r** [comment]
I have one more thing I can think of that could be the problem. I'll get back to you once I'm done.

**Comment by Vysp3r** [comment]
Okay, now it should be all good!

**Comment by smotim** [comment]
Wow. Yes, you fixed my problem. Thanks a lot

**Comment by Vysp3r** [comment]
I will publish a new release today on Flathub with the fix. During that time you can use the dev branch and compile it yourself. I will now close the issue since it has been fixed.
